[package]
name = "fbv-data"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fbv-core = { workspace = true }
rusqlite = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

[dev-dependencies]
tempfile = "3"
